<a href="https://colab.research.google.com/github/yh08037/Introduction-to-Intelligent-Systems/blob/master/HW5_1_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 5-1 K-means
## B) Clustering some real data
### 1. Clustering the students in 3 clusters

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import copy


name_file = "./grade_students.csv"

data = pd.read_csv(name_file)

x = np.asarray(data)

I, N = x.shape

K = 3  # given

y = np.zeros((I, 1))


In [0]:
def distortion(x, mu):
    
    result = 0.
    
    _I = x.shape[0]
    _K = mu.shape[1]
    
    for i in range(_I):
        tmp = []
        for k in range(_K):
            tmp.append(np.linalg.norm(x[i]-mu[:, k]) ** 2)
        _argmin = np.argmin(tmp)
        for k in range(_K):
            if k == _argmin:
                result += tmp[_argmin]
    return result

In [108]:
num_init = 10

J_list = []
Mu_list = []

while len(J_list) < num_init:

    mu = np.vstack([np.random.uniform(0, x[:, n].max(), (1, K)) for n in range(N)])

    J_previous = 0.
    J_present = 0.

    epsilon = 0.0001
    cnt = 0

    mu_list = []
    
    
    while cnt < 1 or abs(J_present - J_previous) > epsilon:
        for i in range(I):
            tmp = []
            for k in range(0, K):
                tmp.append(np.linalg.norm(x[i]-mu[:, k]))
            y[i] = np.argmin(tmp)

        for k in range(K):
            cnt1 = 0
            mu[:, k] = np.zeros(N)
            for i in range(I):
                if y[i, 0] == k:
                    mu[:, k] += x[i]
                    cnt1 += 1
            if cnt1 > 0:
                mu[:, k] /= cnt1

        bad_init = False

        J_previous = J_present
        J_present = distortion(x, mu)
        cnt += 1

        print('iteration', cnt)
        print("mu_k\n", mu)
        print('distortion\n', J_present)
        print()
        
        mu_list.append(mu.copy())
        
        for k in range(K):
            if (mu[:, k] == np.zeros(N)).all():
                break
        else:
            continue
        
        break
         
        
    else:
        J_list.append(J_present)
        Mu_list.append(copy.deepcopy(mu_list))
    
    print('-----------------------------------------------------')

iteration 1
mu_k
 [[5.00720981e-01 0.00000000e+00 1.00000000e+00]
 [7.42231435e+00 0.00000000e+00 4.50000000e+00]
 [5.21339402e+02 0.00000000e+00 4.32000000e+02]
 [5.31455660e+02 0.00000000e+00 5.33000000e+02]
 [5.67824982e+02 0.00000000e+00 5.66000000e+02]
 [5.14709625e+02 0.00000000e+00 3.30000000e+02]]
distortion
 46333101.75606948

-----------------------------------------------------
iteration 1
mu_k
 [[1.00000000e+00 0.00000000e+00 5.00720981e-01]
 [4.05000000e+01 0.00000000e+00 7.40933670e+00]
 [5.38000000e+02 0.00000000e+00 5.21301190e+02]
 [5.73000000e+02 0.00000000e+00 5.31441240e+02]
 [6.96500000e+02 0.00000000e+00 5.67777938e+02]
 [5.25000000e+02 0.00000000e+00 5.14639329e+02]]
distortion
 46230069.1958986

-----------------------------------------------------
iteration 1
mu_k
 [[5.00810957e-01 1.00000000e+00 0.00000000e+00]
 [7.42097675e+00 9.00000000e+00 0.00000000e+00]
 [5.21320418e+02 4.48000000e+02 0.00000000e+00]
 [5.31447828e+02 5.78000000e+02 0.00000000e+00]
 [5.678

In [109]:
Mu_optimal = Mu_list[np.argmin(J_list)]
mu_optimal = Mu_optimal[-1]
print(mu_optimal)

[[7.26430518e-01 2.52148997e-01 4.72186287e-01]
 [8.65885559e+00 6.60816619e+00 6.93143596e+00]
 [4.64508447e+02 5.95224928e+02 5.21754204e+02]
 [4.91587466e+02 5.77361032e+02 5.35369987e+02]
 [5.41401090e+02 5.99065903e+02 5.69925830e+02]
 [4.57405450e+02 5.80020057e+02 5.20578698e+02]]


### 2. Interpreting results
As follows, we can cluster the students in three clusters, that is weak, average and gifted. Each of these are cluster 0, cluster 1 and cluster 2. The students of 'weak' cluster tend to absent, get free lunch more, and the scores of all subjects are lower. In contrast, The studernts of 'gifted' cluster have a tendency to get higher scores in exams,  less free lunch and absent.

In [112]:
cluster = [x[(y==k)[:,0]] for k in range(K)]
mean = [np.mean(cluster[k], axis=0) for k in range(K)]

for k in range(K):
    print('cluster %d\n' %k, cluster[k])
    print('freelunch\tabsent\t\treadscore\tmathscore\tlisteningscore\twordscore')
    for num in mean[k]:
        print('%f\t' %num, end='')
    print()
    print()

cluster 0
 [[  0  12 451 507 584 436]
 [  1   4 483 526 529 486]
 [  1   2 433 463 504 426]
 ...
 [  1  22 438 454 529 436]
 [  0   4 478 532 548 481]
 [  1  10 492 479 531 481]]
freelunch	absent		readscore	mathscore	listeningscore	wordscore
0.725938	8.656879	464.574225	491.613921	541.405111	457.498097	

cluster 1
 [[  1   9 516 578 601 493]
 [  1  15 516 505 556 536]
 [  1  11 503 505 541 506]
 ...
 [  1  10 488 545 584 536]
 [  1   9 487 523 574 493]
 [  1   3 487 515 556 506]]
freelunch	absent		readscore	mathscore	listeningscore	wordscore
0.471934	6.932642	521.814335	535.445596	569.979706	520.620898	

cluster 2
 [[  1  24 590 578 580 551]
 [  1   2 564 520 606 577]
 [  0   7 629 592 685 577]
 ...
 [  0   6 629 545 546 601]
 [  1   1 629 549 601 601]
 [  0   7 579 578 625 536]]
freelunch	absent		readscore	mathscore	listeningscore	wordscore
0.252330	6.603584	595.255197	577.356272	599.073835	580.051613	

